### ISSUE TITLE
No "Magento" menu item

### ISSUE THREAD

**Issue by osya** [fulfilio/trytond-magento#64]
I installed trytond-magento module from "develop" branch on Tryton 3.9.0 (I made some PYSON fixes). Module installed successfully. But no menu item "Magento" appears in main menu. If use branch 3.4.1 of trytond-magento then menu item "Magento" appears. Because branch 3.4.1 has file magento.xml which has "menuitem" tag. Develop branch has no "menuitem" tag in any file. So, how are you using trytond-magento?

**Comment by tarunbhardwaj** [comment]
Current design is based on sale channel.

Refer: https://github.com/fulfilio/trytond-sale-channel
